[[gobject_introspection]]
arch = "x86_64"
git-tree-sha1 = "798efea70b0f8c279ef1ac40d48f8caa72d1375a"
libc = "glibc"
os = "linux"

    [[gobject_introspection.download]]
    sha256 = "fd9735b098336cf62524325c338cffde7ea073cd294fa7526636809cda6a9318"
    url = "https://github.com/JuliaBinaryWrappers/gobject_introspection_jll.jl/releases/download/gobject_introspection-v1.74.0+0/gobject_introspection.v1.74.0.x86_64-linux-gnu.tar.gz"
