[[gobject_introspection]]
arch = "x86_64"
git-tree-sha1 = "1a24f1542fde4903d914fd8348705edab400c1cb"
libc = "glibc"
os = "linux"

    [[gobject_introspection.download]]
    sha256 = "fc13aacd14e0b7446bc2ed9a805064905324d37ffab05c3639eb5790d8075a4b"
    url = "https://github.com/JuliaBinaryWrappers/gobject_introspection_jll.jl/releases/download/gobject_introspection-v1.76.1+0/gobject_introspection.v1.76.1.x86_64-linux-gnu.tar.gz"
